version: '3.1'

services:
  api:
    container_name: twitch-chatbot
    command: yarn start:dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3333:3333
    working_dir: /app
    environment:
      - NODE_ENV=development
